# Generated by Django 5.0.6 on 2024-09-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorizer', '0003_chathistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
